name: build-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - jupyter_server
  - pip:
    - jupyterlite===0.1.0b17
    - jupyterlite-xeus-python==0.6.1
    - git+https://github.com/martinRenou/empack.git@python_tzdata_filtering
